server:
  port: 9002

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        boostrap: true
        git:
          enabled: true
          uri: https://github.com/forceattack012/spring-cloud-playground

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka
